### PR TITLE
Make a navbar

### PR DESCRIPTION
**Pull request by EugeneGohh**
Issue #6 

I have made a navbar that allows users to navigate through the site. The navbar acts upon a certain breakpoint, "burger menu" will appear when it reaches mobile view.

#### Preview of the navbar:
**1.**
Untitled

**2.**
Untitled

**3.**
Untitled

### CODE REVIEW

**Comment by toreylittlefield** [comment]
@EugeneGohh I made a comment in discord. Can you allow permission to checkout this branch locally for me since you're using a forked repo? Thanks. That way I can test locally & review the pull request.

**Comment by toreylittlefield** [comment]
@EugeneGohh try checkout out my commit [5dcf805](https://github.com/lorenzojkrl/ecommerce-group-project/pull/14/commits/5dcf805855e6e528c4a2c2f393698aee7aa78071) "move styles for NavBar.js into NarBarStyles.js" for review and see if you think anything broke.

Otherwise I think this looks good to me! Just let me know when you're done reviewing and i'll merge this request. Nice work on the navbar.

**Comment by toreylittlefield** [comment]
The navbar bugs should be fixed with my last commit #c4934b8. Hopefully there is no breaking changing in anything else. @EugeneGohh I recommend you review the few changes I made to fix the bug to see if I messed any of your code.

**Review by toreylittlefield — APPROVED** [review]

**Comment by EugeneGohh** [comment]
The navbar looks great now. It's time to merge. 😃

**Comment by toreylittlefield** [comment]
Squashed and merged it into 1 commit to main. @EugeneGohh great work :)

**Pull request merged**
