### PR TITLE
First & second container

### PR DESCRIPTION
**Pull request by EugeneGohh**
Referring to issue #6, I have made the first container with added text & image of a MacBook. I'll still need to put in some work on refactoring the code for styling. I will start working on the second container soon.

**Status of first container:**
- [x] First container
- [x] Refactor code

**Status of second container:**
- [x] Second container
- [x] Refactor code

### CODE REVIEW

**Comment by toreylittlefield** [comment]
Noted I'll get to this.

**Comment by toreylittlefield** [comment]
@EugeneGohh howdy! 

### Review
I was reviewing some of the work in this draft #21 and my first suggestion is that you need to fetch upstream to get in sync with the main branch. I think your branch is behind. I was going to leave you a comment in Body.js but I am just going to leave you this picture of your work from this #21  PR here (I was reviewing on my local env): 
image

### Your branch is behind
But then I realize that your branch is behind main here. There's already a ThemeProvider component and I move it in #20 to be separated out from App.js by moving it to it's own folder / file, just throw in your default styling there so you can reuse it throughout the whole App and that way you don't need to repeat yourself & keep it D.R.Y. & reduce complexity. Your branch here is behind because I don't see that file & folder from #20 `frontend\src\theme-style\materialtheme.js`

image


### Ignore if...
 Unless you had a specific reason why you wanted to create another ThemeProvider component then ignore my suggestions above.


### More Review Pending 
I'll review more later after I hear back from you about this. If anythings confusing just give me a shout. Hope this is helpful.

**Review by toreylittlefield — COMMENTED** [review]
See my comments about this branch ( I think it's behind) in the conversation section for this #21 . In short:
- I think you branch is behind
- I don't think you need another ThemeProvider & createMuiTheme useless there's a specific reason you're doing that. Once you fetch upstream and get in sync you can just throw whatever you need inside of the `ThemeProvider ` component in `frontend\src\theme-style\materialtheme.js` which already wraps all of `App.js`
- Suggestion: For consistency do you want to move your sections/containers into their own files as I have already done for example with container 3 i.e. like example: `frontend\src\components\Containers\TrustBadgeContainer.js`? Then just import the components like: 
```
import { TrustBadgeContainer } from "../Containers/TrustBadgeContainer";

      {/* Third container */}
      <TrustBadgeContainer classes={classes} />
```

**Comment by EugeneGohh** [comment]
I have made some changes. The changes include:

1. Refactored code for `Body.js`.
2. Separating the first container into another file. This change includes creating another file for styling named `FirstContainerStyle.js`. Then import the style into `FirstContainer.js`. After making the first container, I have exported it to be able to use it in `Body.js`.
3. Deleted `BodyStyles.js` since the file is not being used.
4. I have renamed `materialtheme.js` to `materialTheme.js` because it looks more conventional I guess. I am just following the of the naming conventions. 😐
5. Added `responsiveFontSizes()` in `materialTheme.js`. I'm not sure if I added it correctly, more info about it here (https://material-ui.com/customization/typography/).
6. In `App.js`, I renamed `import { Theme } from '../../theme-style/materialtheme'` to `import { Theme } from '../../theme-style/materialTheme'`.
7. In `Body.js`, I have imported `FirstContainer.js`. I have added `<section>` not sure if it is SEO friendly, I am following Semantic HTML. I have deleted `classes={classes}` on `<TrustBadgeContainer>` because I am not really sure what it does, let me know if you have any reasons for that I can always add it back.
8. Checked, my branch is up to date.

**Comment by EugeneGohh** [comment]
For second container, I have made some changes to it:

1. Add illustration to the container.
2. Separate `secondContainer` into a component then import to `Body.js`.
3. Use `vh` and `vw`. Remove `ch`.

For first container, I have made the following change:
1. Use `vh` and `vw`. Remove `ch`.

**Pull request closed without merging**
