### PR TITLE
Create Frontend folder & move files/folders

### LINKED ISSUE #5: Frontend / Client should be inside a separate folder
@EugeneGohh Front / Client should be inside a separate folder not nested inside of the backend / server folder. 
- there should be one front-end (or client) and one back-end (or server) project directories. I guess they would probably share one parent directory folder i.e. "project-folder"
- This separation is necessary because for some reasons I am aware of but the biggest reason is the package.json and "build" (for production)  will not work correctly or have conflicts. Not a great explanation but that's the gist of it.

Example from Stackoverflow:
**Client Folder**
```
- /client 
-- /src
...
-- index.js
-- registerServiceWorker.js
- .gitignore
- package-lock.json
- package.json
```

**Server Folder**
```
- /server
- /models
-- item.js
- /node.modules
-- ...
- server.js
- package-lock.json
- package.json
```

### PR DESCRIPTION
**Pull request by toreylittlefield**
Created a folder labeled "frontend" and moved the relevant files and folders to the frontend folder. Is working locally without an issue I can detect. Had both the server and react frontend working at the same time without an issue.

Resolves and closes #5

### CODE REVIEW

**Review by EugeneGohh — APPROVED** [review]
Looks clean

**Review by CraigDoesCode — APPROVED** [review]

**Comment by CraigDoesCode** [comment]
hey looks like there is a conflict with this commit i just realised after I approved, I think we'll need to resolve that before we're able to commit

**Comment by toreylittlefield** [comment]
@craig1001 @EugeneGohh weird I didn't touch Body.js (hahaha just realized that sounds funny). Anyways, all I did was move files/folders. I don't know how / or can't see the conflicts locally. Anyone can help?

I followed these instructions but I get a fatal flaw message:
"Step 1: From your project repository, bring in the changes and test.

git fetch origin
git checkout -b Frontend-Folder origin/Frontend-Folder
git merge main
Step 2: Merge the changes and update on GitHub.

git checkout main
git merge --no-ff Frontend-Folder
git push origin main"

**Comment by EugeneGohh** [comment]
> @craig1001 @EugeneGohh weird I didn't touch Body.js (hahaha just realized that sounds funny). Anyways, all I did was move files/folders. I don't know how / or can't see the conflicts locally. Anyone can help?
> 
> I followed these instructions but I get a fatal flaw message:
> "Step 1: From your project repository, bring in the changes and test.
> 
> git fetch origin
> git checkout -b Frontend-Folder origin/Frontend-Folder
> git merge main
> Step 2: Merge the changes and update on GitHub.
> 
> git checkout main
> git merge --no-ff Frontend-Folder
> git push origin main"

I followed the steps but the last step will require merging the `Frontend-Folder` branch to the `main` branch.

**Comment by toreylittlefield** [comment]
> > @craig1001 @EugeneGohh weird I didn't touch Body.js (hahaha just realized that sounds funny). Anyways, all I did was move files/folders. I don't know how / or can't see the conflicts locally. Anyone can help?
> > 
> > I followed these instructions but I get a fatal flaw message:
> > "Step 1: From your project repository, bring in the changes and test.
> > 
> > git fetch origin
> > git checkout -b Frontend-Folder origin/Frontend-Folder
> > git merge main
> > Step 2: Merge the changes and update on GitHub.
> > 
> > git checkout main
> > git merge --no-ff Frontend-Folder
> > git push origin main"
> 
> I followed the steps but the last step will require merging the `Frontend-Folder` branch to the `main` branch.

Weird because it won't allow me to do it in my local environment even after I follow the steps. Is it possible you can do the merge or does it have to be me I can't understand what the problem is.

**Comment by EugeneGohh** [comment]
> > > @craig1001 @EugeneGohh weird I didn't touch Body.js (hahaha just realized that sounds funny). Anyways, all I did was move files/folders. I don't know how / or can't see the conflicts locally. Anyone can help?
> > > I followed these instructions but I get a fatal flaw message:
> > > "Step 1: From your project repository, bring in the changes and test.
> > > git fetch origin
> > > git checkout -b Frontend-Folder origin/Frontend-Folder
> > > git merge main
> > > Step 2: Merge the changes and update on GitHub.
> > > git checkout main
> > > git merge --no-ff Frontend-Folder
> > > git push origin main"
> > 
> > 
> > I followed the steps but the last step will require merging the `Frontend-Folder` branch to the `main` branch.
> 
> Weird because it won't allow me to do it in my local environment even after I follow the steps. Is it possible you can do the merge or does it have to be me I can't understand what the problem is.

Basically, I deleted my forked repo, fork it again and open on VS code to follow the commands that are given. It works but I think that's not a good practice overall. I have Googled this conflict problem in the first place but none of them work.

**Comment by toreylittlefield** [comment]
> > > > @craig1001 @EugeneGohh weird I didn't touch Body.js (hahaha just realized that sounds funny). Anyways, all I did was move files/folders. I don't know how / or can't see the conflicts locally. Anyone can help?
> > > > I followed these instructions but I get a fatal flaw message:
> > > > "Step 1: From your project repository, bring in the changes and test.
> > > > git fetch origin
> > > > git checkout -b Frontend-Folder origin/Frontend-Folder
> > > > git merge main
> > > > Step 2: Merge the changes and update on GitHub.
> > > > git checkout main
> > > > git merge --no-ff Frontend-Folder
> > > > git push origin main"
> > > 
> > > 
> > > I followed the steps but the last step will require merging the `Frontend-Folder` branch to the `main` branch.
> > 
> > Weird because it won't allow me to do it in my local environment even after I follow the steps. Is it possible you can do the merge or does it have to be me I can't understand what the problem is.
> 
> Basically, I deleted my forked repo, fork it again and open on VS code to follow the commands that are given. It works but I think that's not a good practice overall. I have Googled this conflict problem in the first place but none of them work.

So do I have to do this or is it fixed? Can we merge now? Do we know why this happened anyways so we can avoid it in the future if we have to move files or whatever?

**Review by toreylittlefield — COMMENTED** [review]
@EugeneGohh sure you can edit and make changes but what's there to change???

**Review by EugeneGohh — CHANGES_REQUESTED** [review]
I found the issue, probably it is on `comments`. Can you copy-paste this code into `Body.js`? I have tried to edit it but after the edit, I viewed it nothing changed.

https://github.com/lorenzojkrl/ecommerce-group-project/blob/main/src/components/Body/Body.js

**Review by toreylittlefield — COMMENTED** [review]
@EugeneGohh try to give this approval since I cannot

**Review by EugeneGohh — APPROVED** [review]

**Comment by toreylittlefield** [comment]
@EugeneGohh @craig1001 I am closing this and we'll try it from @EugeneGohh 's local because he has been updating the frontend files so maybe that's where the conflict is. We'll open another pull request and hopefully no conflict

**Pull request closed without merging**
